MVC.Ferroviaria/Controllers/HorarioController.cs
using Ferroviaria.Consumer;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Modelos.Ferroviario.Modelos;

namespace MVC.Ferroviaria.Controllers
{
    public class HorarioController : Controller
    {
        public ActionResult Index(int id)
        {
            
            var horarios = Crud<Schedule>.GetBy("Ruta", id);
            return View(horarios);
        }

        // GET: HorarioController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: HorarioController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HorarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HorarioController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: HorarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: HorarioController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: HorarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC.Ferroviaria/Controllers/VagonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Modelos.Ferroviario.Modelos;
using Ferroviaria.Consumer;
using Modelos.Ferroviario.DTOS;

namespace MVC.Ferroviaria.Controllers
{
    public class VagonController : Controller
    {
        // GET: VagonController
        public ActionResult Index(int id)
        {
            var vagones = Crud<TrainCar>.GetBy("Train", id);
            TempData["HorarioId"] = id;
            TempData.Keep("HorarioId");
            return View(vagones);
        }

        // GET: VagonController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VagonController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VagonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VagonController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VagonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VagonController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VagonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC.Ferroviaria/Views/Horario/Index.cshtml
@using Modelos.Ferroviario.DTOS
@model IEnumerable<Modelos.Ferroviario.Modelos.Schedule>

@{
    ViewData["Title"] = "Index";
}

<h1>Horarios Disponibles</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoraSalida)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraLlegada)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Ruta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tren)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoraSalida)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HoraLlegada)
            </td>
            <td>
                    @($"{item.Ruta.CiudadInicio} - {item.Ruta.CiudadDestino}")
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tren.Nombre)
            </td>
            <td>
                @Html.ActionLink("Ver Vagones", "Index","Vagon", new { id = item.TrenId}) 

            </td>
        </tr>
}
    </tbody>
</table>