MVC.Ferroviaria/Controllers/SeatController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Modelos.Ferroviario.Modelos;
using Ferroviaria.Consumer;

namespace MVC.Ferroviaria.Controllers
{
    public class SeatController : Controller
    {
        // GET: SeatController
        public ActionResult Index(int id)
        {
           
            var data = Crud<Seat>.GetBy("TrainCar", id);
            return View(data);
        }

        // GET: SeatController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SeatController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SeatController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SeatController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SeatController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SeatController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SeatController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC.Ferroviaria/Controllers/VagonController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Modelos.Ferroviario.Modelos;
using Ferroviaria.Consumer;
using Modelos.Ferroviario.DTOS;

namespace MVC.Ferroviaria.Controllers
{
    public class VagonController : Controller
    {
        // GET: VagonController
        public ActionResult Index(int id)
        {
            var vagones = Crud<TrainCar>.GetBy("Train", id);
            TempData["HorarioId"] = id;
            TempData.Keep("HorarioId");
            return View(vagones);
        }

        // GET: VagonController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VagonController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: VagonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VagonController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: VagonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: VagonController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: VagonController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MVC.Ferroviaria/Views/Vagon/Index.cshtml
@model IEnumerable<Modelos.Ferroviario.Modelos.TrainCar>

@{
    ViewData["Title"] = "Vagones Disponibles";
    var vagones = Model.ToList();
}

<h1>Vagones Disponibles</h1>

<table class="table table-bordered">
    <thead class="table-primary">
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().CantidadAsientos)</th>
            <th>@Html.DisplayNameFor(model => model.First().Tipo)</th>
            <th>@Html.DisplayNameFor(model => model.First().Estado)</th>
            <th>@Html.DisplayNameFor(model => model.First().Tren)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in vagones)
        {
            <tr>
                <td>@item.CantidadAsientos</td>
                <td>@item.Tipo</td>
                <td>@item.Estado</td>
                <td>@item.Tren?.Nombre</td>
            </tr>
        }
    </tbody>
</table>

<hr />

<h4>Selecciona un vagón para continuar:</h4>

<div class="d-flex flex-wrap gap-4">
    @for (int i = 0; i < vagones.Count; i++)
    {
        <div class="text-center">
            <a asp-controller="Seat"
               asp-action="Index"
               asp-route-id="@vagones[i].Id">
                <img src="~/img/vagon.png"
                     alt="Vagón @(i + 1)"
                     style="width:150px; height:auto;"
                     class="img-thumbnail" />
            </a>
            <p class="mt-2 fw-bold">Vagón @(i + 1)</p>
        </div>
    }
</div>

@if (ViewBag.Mensaje != null)
{
    <div class="alert alert-success mt-3">
        @ViewBag.Mensaje
    </div>
}